server:
  port: 8206
spring:
  application:
    name: service-oss
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  cloud:
    nacos:
      discovery:
        server-addr: nacos.ruikai.ltd:80

aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    accessKeyId: *
    secret: *
    bucket: *