spring:
  application:
    name: service-sms
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  mail:
    host: smtp.163.com
    username: 123456@163.com
    password: *
    default-encoding: UTF-8
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 0
    lettuce:
      pool:
        max-wait: -1
        max-idle: 5
        min-idle: 0

server:
  port: 8204
